[build]
  base = "/frontend"
  publish = "/frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.0.0"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
